[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/merci"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200